// PR-comment markdown: a short, scannable post for code review.
// Begins with an HTML comment marker so a bot can update it in place
// (look for <!-- ts-crap-report --> in existing comments and replace).

import type { CrapEntry, ReportMeta } from "../options.js"
import type { DeltaRow, DeltaSummary } from "../delta.js"
import { sortEntries } from "./human.js"

export interface PrCommentOptions {
  threshold: number
  top?: number
  /** Optional baseline diff. When provided, regressions and improvements
   * are surfaced; otherwise the comment is a flat top-N table. */
  delta?: { rows: DeltaRow[]; summary: DeltaSummary }
}

const MARKER = "<!-- ts-crap-report -->"

export function renderPrComment(
  entries: CrapEntry[],
  meta: ReportMeta,
  opts: PrCommentOptions
): string {
  const top = opts.top ?? 10
  const isCrap = entries.some((e) => e.mode === "crap")
  const lines: string[] = [MARKER]
  lines.push("## 🧪 ts-crap")
  lines.push("")
  lines.push(headline(entries, meta, opts.threshold, isCrap))
  lines.push("")

  if (opts.delta) renderDelta(lines, opts.delta, top, isCrap)
  else renderFlat(lines, entries, top, isCrap)

  const suppressed = entries.filter((e) => e.suppressed)
  if (suppressed.length) renderSuppressed(lines, suppressed)

  lines.push("")
  lines.push(
    `<sub>Generated by [ts-crap](https://github.com/dedalik/ts-crap) ` +
      `v${meta.version} · threshold ${opts.threshold} · ${meta.generatedAt}</sub>`
  )
  return lines.join("\n") + "\n"
}

function headline(
  entries: readonly CrapEntry[],
  meta: ReportMeta,
  threshold: number,
  isCrap: boolean
): string {
  const counts = { error: 0, warning: 0, info: 0, ok: 0 }
  for (const e of entries) counts[e.severity]++
  const mode = isCrap ? "CRAP" : "complexity-only"
  const cov = meta.coverageSource
    ? ` · coverage \`${meta.coverageSource.path}\``
    : ""
  return (
    `**${entries.length}** functions analyzed in ${mode} mode${cov}. ` +
    `Threshold ${threshold}: ` +
    `🔴 ${counts.error} error · 🟠 ${counts.warning} warning · 🟡 ${counts.info} info · 🟢 ${counts.ok} ok.`
  )
}

function renderDelta(
  lines: string[],
  delta: { rows: DeltaRow[]; summary: DeltaSummary },
  top: number,
  isCrap: boolean
): void {
  const regressions = delta.rows.filter((r) => r.kind === "regression").slice(0, top)
  if (regressions.length) {
    lines.push(`### 🚨 Regressions (${delta.summary.regression})`)
    lines.push("")
    lines.push(deltaTable(regressions, isCrap))
    lines.push("")
  } else {
    lines.push(`### ✅ No regressions`)
    lines.push("")
  }

  const news = delta.rows.filter((r) => r.kind === "new").slice(0, top)
  if (news.length) {
    lines.push(`### ➕ New (${delta.summary.new})`)
    lines.push("")
    lines.push(deltaTable(news, isCrap))
    lines.push("")
  }

  const improvements = delta.rows.filter((r) => r.kind === "improved")
  if (improvements.length) {
    lines.push("<details><summary>📉 Improvements (" + improvements.length + ")</summary>")
    lines.push("")
    lines.push(deltaTable(improvements.slice(0, top), isCrap))
    lines.push("")
    lines.push("</details>")
    lines.push("")
  }
}

function renderFlat(
  lines: string[],
  entries: CrapEntry[],
  top: number,
  isCrap: boolean
): void {
  const sorted = sortEntries(entries).slice(0, top)
  if (sorted.length === 0) {
    lines.push("No functions above the threshold. Nice.")
    return
  }
  lines.push(`### Top ${sorted.length} by score`)
  lines.push("")
  lines.push(flatTable(sorted, isCrap))
}

function flatTable(rows: CrapEntry[], isCrap: boolean): string {
  const head = isCrap
    ? "| Sev | Score | CC | Cog | Cov | Function | Location |"
    : "| Sev | Score | CC | Cog | Function | Location |"
  const sep = isCrap
    ? "| :-: | --: | --: | --: | --: | --- | --- |"
    : "| :-: | --: | --: | --: | --- | --- |"
  const body = rows.map((e) => {
    const sev = sevEmoji(e.severity)
    const fn = "`" + safe(e.function) + "`"
    const loc = "`" + safe(e.file) + ":" + e.line + "`"
    return isCrap
      ? `| ${sev} | ${e.score.toFixed(1)} | ${e.complexity} | ${e.cognitive} | ${covCell(e)} | ${fn} | ${loc} |`
      : `| ${sev} | ${e.score.toFixed(1)} | ${e.complexity} | ${e.cognitive} | ${fn} | ${loc} |`
  })
  return [head, sep, ...body].join("\n")
}

function deltaTable(rows: DeltaRow[], isCrap: boolean): string {
  const head = isCrap
    ? "| Δ | Score | Was | CC | Cog | Cov | Function | Location |"
    : "| Δ | Score | Was | CC | Cog | Function | Location |"
  const sep = isCrap
    ? "| --: | --: | --: | --: | --: | --: | --- | --- |"
    : "| --: | --: | --: | --: | --: | --- | --- |"
  const body = rows.map((r) => {
    const e = r.current ?? r.baseline!
    const score = r.current ? r.current.score.toFixed(1) : "-"
    const was = r.baseline ? r.baseline.score.toFixed(1) : "-"
    const fn = "`" + safe(e.function) + "`"
    const loc = "`" + safe(e.file) + ":" + e.line + "`"
    const delta = (r.delta > 0 ? "+" : "") + r.delta.toFixed(1)
    return isCrap
      ? `| ${delta} | ${score} | ${was} | ${e.complexity} | ${e.cognitive} | ${covCell(e)} | ${fn} | ${loc} |`
      : `| ${delta} | ${score} | ${was} | ${e.complexity} | ${e.cognitive} | ${fn} | ${loc} |`
  })
  return [head, sep, ...body].join("\n")
}

function renderSuppressed(lines: string[], rows: readonly CrapEntry[]): void {
  lines.push(`<details><summary>🤫 Suppressed (${rows.length})</summary>`)
  lines.push("")
  lines.push("| Function | Location | Reason |")
  lines.push("| --- | --- | --- |")
  for (const e of rows) {
    lines.push(
      `| \`${safe(e.function)}\` | \`${safe(e.file)}:${e.line}\` | ${safe(e.suppressed?.reason ?? "")} |`
    )
  }
  lines.push("")
  lines.push("</details>")
}

function sevEmoji(s: CrapEntry["severity"]): string {
  return s === "error" ? "🔴" : s === "warning" ? "🟠" : s === "info" ? "🟡" : "🟢"
}

function covCell(e: CrapEntry): string {
  return e.coverage == null ? "-" : `${e.coverage.toFixed(1)}%`
}

function safe(s: string): string {
  return s.replace(/\|/g, "\\|")
}
